---
title: "boba_project_week11"
output: html_document
date: "2023-10-22"
---

#Import data
```{r}
library(stringr)
library(dplyr)
#this dataset was scraped to include reviews, longitudes, and latitudes
predictors <- read.csv("/Users/violetevans/xiaolongbao/Data/all_logi.csv")
length(predictors)
View(predictors$Rating)
```

#creating NYC data frame feature columns
```{r}
nyc<- predictors[predictors$source=="nyc_boba", 1:15]
rownames(nyc) <- 1:nrow(nyc)
nyc_rating <- predictors$Rating[predictors$source == "nyc_boba"]
all_cat<- unlist(strsplit(nyc$Categories, ","))
all_cat<- str_trim(all_cat)
#26 unique categories
clean_names <- janitor::make_clean_names(unique(all_cat))
var <- paste0(clean_names,"_ind")
mat=  matrix(0, nrow(nyc), 19)
colnames(mat)<- var
df <- data.frame(mat)
nyc_df <- cbind(nyc, df)
full_names<- unique(all_cat)
for (i in seq_along(1:19)){
  for (j in 1:nrow(nyc)){
    nyc_df[[var[i]]][j]= grepl(full_names[i], nyc$Categories[j])
  }
}
head(nyc_df)
#check for missing values
missing_counts <- colSums(is.na(nyc_df))
missing_counts

#We don't need the following columns, this is what we used to identify the shops and scrape them 
nyc_df$bubble_tea_ind<- NULL
nyc_df$Phone <- NULL
nyc_df$Categories<- NULL
nyc_df$Street.Address <- NULL
nyc_df$Address<- NULL
#The columns with binary values should become factors
nyc_df[,c(3,11:30)]<- lapply(nyc_df[,c(3,11:30)], function(col) factor(col))
#Make columns their appropriate types
nyc_df$Rating <- as.numeric(nyc_df$Rating)
nyc_df$Authenticity <- as.numeric(nyc_df$Authenticity)
nyc_df$Restaurant <- as.numeric(nyc_df$Restaurant)
nyc_df$chain <- as.numeric(nyc_df$chain)
```


```{r}
raleigh<- predictors[predictors$source=="raleigh_boba",1:15]
rownames(raleigh) <- 1:nrow(raleigh)
raleigh_rating<- predictors$Rating[predictors$source == "raleigh_boba"]
all_cat1<- unlist(strsplit(raleigh$Categories, ","))
all_cat1 <- str_trim(all_cat1)
unique(all_cat1)
#16 unique categories
clean_names1 <-janitor::make_clean_names(unique(all_cat1))
var1 <- paste0(clean_names1,"_ind")
mat1<- matrix(0, nrow(raleigh), 16)
colnames(mat1)<- var1
df1 <- data.frame(mat1)
raleigh_df <- cbind(raleigh, df1)
full_names1 <- unique(all_cat1)
for (i in seq_along(1:16)){
  for (j in 1:nrow(raleigh)){
    raleigh_df[[var1[i]]][j]= grepl(full_names1[i], raleigh$Categories[j])
  }
}

#We don't need the following columns, this is what we used to identify the shops and scrape them 
raleigh_df$bubble_tea_ind<- NULL
raleigh_df$Phone <- NULL
raleigh_df$Categories<- NULL
raleigh_df$Address <- NULL
raleigh_df$Street.Address <- NULL
#Let's check missing counts before building linear regression
missing_counts <- colSums(is.na(raleigh_df))
missing_counts
#impute the 3 missing street addresses we found
for (col in colnames(raleigh_df)){
  count= sum(is.na(raleigh_df[[col]]))
  if (count >0){
    print(sum(is.na(raleigh_df[[col]])))
    raleigh_df[[col]]<- ifelse(is.na(raleigh_df[[col]]),"M", raleigh_df[[col]])
  }  
}
#Make columns their appropriate types
# Assuming your_factor is the factor variable
raleigh_df$Rating <- as.numeric(raleigh$Rating)
raleigh_df$Authenticity <- as.numeric(raleigh_df$Authenticity)
raleigh_df$Restaurant <- as.numeric(raleigh_df$Restaurant)
raleigh_df$chain<- as.numeric(raleigh_df$chain)
```
#Now we have completed Raleigh and NYC data frames with all columns, including binary indicator variables

#NYC Variable Selection
```{r}
nyc_df[, c(9:30)] <- lapply(nyc_df[, c(9:30)], function(col) factor(col))
#Do forward selection for the columns that explain rating
full.model.nyc <- lm(Rating ~  ., data = nyc_df[,c(2, 9:30)])
empty.model.nyc <- lm(Rating ~ 1, data = nyc_df[,c(2,9:30)])
for.model.nyc <- step(empty.model.nyc, scope = list(lower = empty.model.nyc, upper = full.model.nyc), direction = "forward", k = 2)
step.model.nyc <- step(empty.model.nyc, scope = list(lower = empty.model.nyc, upper = full.model.nyc), direction = "both", k = 2) 
```


#Raleigh Variable Selection 
```{r}
#Make the binary columns 13 to 31 as factors
raleigh_df[, c(9:27)] <- lapply(raleigh_df[, c(9:27)], function(col) factor(col))
#Rating should be numeric
raleigh_df$Rating <- as.numeric(raleigh_df$Rating)
raleigh_df$random <- NULL
full.model <- lm(Rating ~  ., data = raleigh_df[,c(2,4:5,9:26)])
empty.model <- lm(Rating ~ 1, data = raleigh_df[,c(2,4:5,9:26)])
for.model.raleigh <- step(empty.model, scope = list(lower = empty.model, upper = full.model), direction = "forward", k = 2)
step.model.raleigh <- step(empty.model, scope = list(lower = empty.model, upper = full.model), direction = "both", k = 2) 
```

#Random Forest Predictions for Raleigh and NYC
```{r}
library(randomForest)
#Run a random forest model for Raleigh
raleigh_df<- as.data.frame(raleigh_df)
raleigh_df$random<- rnorm(43)
set.seed(12345)
rf.raleigh <- randomForest(Rating ~ ., data = raleigh_df, ntree = 250, importance = TRUE)
varImpPlot(rf.raleigh ,
           sort = TRUE,
           n.var = 10,
           main = "Top 10 - Variable Importance for Raleigh", type = 1)
#Run a random forest model for NYC
nyc_df <- as.data.frame(nyc_df)
nyc_df$random<- rnorm(70)
set.seed(12345)
rf.nyc <- randomForest(Rating ~ ., data = nyc_df, ntree = 250, importance = TRUE)
varImpPlot(rf.nyc,
           sort = TRUE,
           n.var = 10,
           main = "Top 10 - Variable Importance for NYC", type = 1)
```

#Boxplot
```{r}
boxplot(Rating ~ Authenticity, data = raleigh_df, 
        main = "Boxplot of Raleigh Boba by Authenticity",
        xlab = "Authenticity",
        ylab = "Rating",
        col = c("skyblue", "salmon"),
        border = "black")
boxplot(Rating ~ Authenticity, data = nyc_df, 
        main = "Boxplot of NYC Boba by Authenticity",
        xlab = "Authenticity",
        ylab = "Rating",
        col = c("skyblue", "salmon"),
        border = "black")
boxplot(Rating ~ source, data = predictors)
```


